spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    username: root
    password: 8cy8do
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      names: ${job.name:}
logging:
  level:
    org.springframework.batch: debug
